baseURL = "https://rafa.wtf/"
title = "Rafa G√≥mez Casas | Cofundador de Codely"
languageCode = "es-ES"

disableHugoGeneratorInject = true
defaultContentLanguage = "es"
preserveTaxonomyNames = true
paginate = 100

[permalinks]
  articulos = "/:filename"
  charlas = "/charlas/:filename"
  etc = "/:filename"

[params]
  description = "Art√≠culos, v√≠deos, recursos y tutoriales sobre Desarrollo Web, Frontend, Performance Web ‚ö°Ô∏è, Javascript ‚òïÔ∏è, React ‚öõÔ∏è y CSS üé®"
  image = "/favicon/apple-touch-icon.png"

[markup]
  [markup.highlight]
    guessSyntax = true
    noClasses = false
    tabWidth = 2

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
